Pump:
  required:
    - id
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: |
    This entity contains a harmonised description of a generic pump made for the Water Network Management domain.
    This entity is primarily associated with the water management vertical and related IoT applications.

    Main files in this directory are:
    Pump Entity schema.
    Pump Entity Example.
    Pump Entity Spec.
