--- 
components: 
  schemas: 
    Pump: 
      $ref: "https://smart-data-models.github.io/dataModel.WaterNetworkManagement/Pump/model.yaml#/Pump"
info: 
  description: |
    This entity contains a harmonised description of a generic pump made for the Water Network Management domain.
    This entity is primarily associated with the water management vertical and related IoT applications.

    Main files in this directory are:
    Pump Entity schema.
    Pump Entity Example.
    Pump Entity Spec.
    
  title: Pump
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - Pump
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.WaterNetworkManagement/Pump/examples/example-normalized-ld.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
