--- 
components: 
  schemas: 
    Curve: 
      $ref: "https://smart-data-models.github.io/dataModel.WaterNetworkManagement/Curve/model.yaml#/Curve"
info: 
  description: |
    This entity contains an harmonised description of a generic curve made for the Water Network 
    Management domain. This entity is primarily associated with the water management vertical 
    and related IoT applications.
  title: Curve
  version: "1.0.0"
openapi: "3.0.0"

# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - Curve
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.WaterNetworkManagement/Curve/examples/example-normalized-ld.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
